export default {
    Server: Symbol.for('Server'),
    Logger: Symbol.for('Logger'),
    Database: Symbol.for('Database'),
    FireAuth: Symbol.for('FireAuth'),

    Call: Symbol.for('Call'),
    PaymentByMomo: Symbol.for('PaymentByMomo'),

    // Do not remove the next line, it's using for code generator
    // SYMBOL //
    CouponService: Symbol.for('CouponService'),
    CouponRepository: Symbol.for('CouponRepository'),

    UserRepository: Symbol.for('UserRepository'),
    RoomRepository: Symbol.for('RoomRepository'),
    TutorRepository: Symbol.for('TutorRepository'),
    CourseRepository: Symbol.for('CourseRepository'),
    SessionRepository: Symbol.for('SessionRepository'),
    BookingRepository: Symbol.for('BookingRepository'),
    StudentRepository: Symbol.for('StudentRepository'),
    CategoryRepository: Symbol.for('CategoryRepository'),
    UserActivityRepository: Symbol.for('UserActivityRepository'),
    TeachingDataRepository: Symbol.for('TeachingDataRepository'),
    LearningDataRepository: Symbol.for('LearningDataRepository'),
    TutorReviewerRepository: Symbol.for('TutorReviewerRepository'),
    LearningStackRepository: Symbol.for('LearningStackRepository'),
    ScheduledTaskRepository: Symbol.for('ScheduledTaskRepository'),
    TutorReviewerSummaryRepository: Symbol.for('TutorReviewerSummaryRepository'),

    UserService: Symbol.for('UserService'),
    AuthService: Symbol.for('AuthService'),
    RoomService: Symbol.for('RoomService'),
    TutorService: Symbol.for('TutorService'),
    CourseService: Symbol.for('CourseService'),
    BookingService: Symbol.for('BookingService'),
    StudentService: Symbol.for('StudentService'),
    SessionService: Symbol.for('SessionService'),
    PaymentService: Symbol.for('PaymentService'),
    TeachingDataService: Symbol.for('TeachingDataService'),
    LearningDataService: Symbol.for('LearningDataService'),
    UserActivityService: Symbol.for('UserActivityService'),
    TutorReviewerService: Symbol.for('TutorReviewerService'),
    LearningStackService: Symbol.for('LearningStackService'),
    ScheduledTaskService: Symbol.for('ScheduledTaskService'),
    TutorReviewerSummaryService: Symbol.for('TutorReviewerSummaryService'),

    UserSeeding: Symbol.for('UserSeeding'),
    TutorSeeding: Symbol.for('TutorSeeding'),
    CourseSeeding: Symbol.for('CourseSeeding'),
    BookingSeeding: Symbol.for('BookingSeeding'),
    SessionSeeding: Symbol.for('SessionSeeding'),
    StudentSeeding: Symbol.for('StudentSeeding'),
    CategorySeeding: Symbol.for('CategorySeeding'),
    UserActivitySeeding: Symbol.for('UserActivitySeeding'),
    TutorReviewerSeeding: Symbol.for('TutorReviewerSeeding')
};
